### ISSUE TITLE
File not found when running auth login

### ISSUE THREAD

**Issue by AleCie** [jahwag/ClaudeSync#72]
### Operating System

Windows 10

### Python Version

3.12

### ClaudeSync Version

0.6.0

### Installation Type

New

### Configuration

{
  "claude_api_url": "https://api.claude.ai/api",
  "compression_algorithm": "none",
  "file_categories": {
    "all_files": {
      "description": "All files not ignored",
      "patterns": [
        "*"
      ]
    },
    "all_source_code": {
      "description": "All source code files",
      "patterns": [
        "*.java",
        "*.py",
        "*.js",
        "*.ts",
        "*.c",
        "*.cpp",
        "*.h",
        "*.hpp",
        "*.go",
        "*.rs"
      ]
    },
    "build_config": {
      "description": "Build configuration files",
      "patterns": [
        "**/pom.xml",
        "**/build.gradle",
        "**/package.json",
        "**/setup.py",
        "**/Cargo.toml",
        "**/go.mod",
        "**/pyproject.toml",
        "**/requirements.txt",
        "**/*.tf",
        "**/*.yaml",
        "**/*.yml",
        "**/*.properties"
      ]
    },
    "production_code": {
      "description": "Production source code",
      "patterns": [
        "**/src/**/*.java",
        "**/*.py",
        "**/*.js",
        "**/*.ts",
        "**/*.vue"
      ]
    },
    "test_code": {
      "description": "Test source code",
      "patterns": [
        "**/test/**/*.java",
        "**/tests/**/*.py",
        "**/test_*.py",
        "**/*Test.java"
      ]
    },
    "uberproject_java": {
      "description": "Uberproject Java + Javascript",
      "patterns": [
        "**/src/**/*.java",
        "**/*.py",
        "**/*.js",
        "**/*.ts",
        "**/*.vue",
        "**/pom.xml",
        "**/build.gradle",
        "**/package.json",
        "**/setup.py",
        "**/Cargo.toml",
        "**/go.mod",
        "**/pyproject.toml",
        "**/requirements.txt",
        "**/*.tf",
        "**/*.yaml",
        "**/*.yml",
        "**/*.properties"
      ]
    }
  },
  "log_level": "INFO",
  "max_file_size": 32768,
  "prune_remote_files": true,
  "submodule_detect_filenames": [
    "pom.xml",
    "build.gradle",
    "package.json",
    "setup.py",
    "Cargo.toml",
    "go.mod"
  ],
  "two_way_sync": false,
  "upload_delay": 0.5
}

### Steps to Reproduce

1. pip install claudesync
2. claudesync auth login
3. claude.ai
4. paste sessionKey, enter
5. enter

### Description

I am getting python error when trying to auth login. Would appreciate any tips or guidelines.

### Logs

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\claudesync.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\claudesync\utils.py", line 263, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\claudesync\cli\auth.py", line 30, in login
    session_key, expiry = provider_instance.login()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\claudesync\providers\base_claude_ai.py", line 100, in login
    self.config.set_session_key("claude.ai", session_key, expires)
  File "C:\Python312\Lib\site-packages\claudesync\configmanager\file_config_manager.py", line 177, in set_session_key
    self.session_key_manager.encrypt_session_key(provider, session_key)
  File "C:\Python312\Lib\site-packages\claudesync\session_key_manager.py", line 66, in encrypt_session_key
    return self._encrypt_rsa(session_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\claudesync\session_key_manager.py", line 90, in _encrypt_rsa
    encrypted_output = subprocess.run(
                       ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by jahwag** [comment]
Hi, you need to have [openssl](https://community.chocolatey.org/packages/openssl) installed.
